### ISSUE TITLE
Check field connectivity proposal

### ISSUE THREAD

**Issue by lkovac153** [execom-eu/connected_scale#2]
Connected scale application should help with managing on-field measuring process. Having that in mind one of the biggest challenges on this project will be to find solution that will help us with maintaining the relation between worker and buckets.

On the plant site workers will be given token of identification and once shift is ended they will bring buckets with themselves. We should find the optimal solution which will help us to match the worker with the buckets they brought. Measuring can be held on the site or on some other place, where buckets will be later transported.

Current proposals for identification tokens:

- Using barcode pairs
- Using RFID

**Expected output**

- [x] Document with explained pros and cons of proposed solutions (have in mind all factors like price, conditions, robustness must be evaluated)
- [x] Check if there are other possible solutions for managing pairs (worker - buckets)

**Comment by zuba1990** [comment]
Document can be found on this [link](https://docs.google.com/document/d/1J1wsVKCz9kfoCgXl6g_roebfLrA3fYiqfRaaXlRsL3I/edit#heading=h.sxx0b8uegvep).
