### ISSUE TITLE
Check Xamarin support for NFC plugin

### ISSUE THREAD

**Issue by lkovac153** [execom-eu/connected_scale#4]
We should have some clue about the NFC support in Xamarin.

Check availability of NFC plugin in both Xamarin.Forms and Xamarin.Native. This can be handy tip for deciding which Xamarin platform we should use.

Expected output:

- [x] Find Xamarin NFC nuget/library and check their functionalities for reading RFID tags.
- [x] Check which versions of android supports NFC and preferably find a list of phones that supports NFC with RFID feature(if one exists at all).
- [x] Create a document with details about technologies used in order to provide functionality.

**Comment by s-grahovac** [comment]
Document with the output of this investigation is available at this link:
[LINK](https://docs.google.com/document/d/1biLf-OalAD9n0lFlgczL_g-ytByGLhPiKs5-Gw8oaWc/edit)
