### ISSUE TITLE
Setup testing infrastructure and define frameworks that will be used.

### ISSUE THREAD

**Issue by lkovac153** [execom-eu/connected_scale#8]
Please provide initial testing infrastructure like tools and frameworks that should be used for testing.
Testing tasks that should be defined:

- Create test case
- Create test scenario
- Bug report template

**Comment by zuba1990** [comment]
Document with the output of this issue is available at this [link](https://drive.google.com/drive/u/0/folders/1jl7WmQ-LevKHtsre7d_7YUs0kcleoZbd).
